# Generated by Django 3.2.7 on 2021-09-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='additional_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
