# Generated by Django 3.2.6 on 2021-08-04 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('allowed_teachers', models.ManyToManyField(related_name='visible_courses', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('help_text', models.TextField(blank=True)),
                ('error_percentage_for_help_text', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='training.course')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('custom', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingTemplateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('difficulty', models.PositiveIntegerField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.topic')),
                ('training_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingtemplate')),
            ],
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='rules',
            field=models.ManyToManyField(through='training.TrainingTemplateRule', to='training.Topic'),
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_sessions', to='training.course')),
                ('trainee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
                ('training_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to='training.trainingtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('difficulty', models.PositiveSmallIntegerField()),
                ('imported_from_exam', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('rendered_text', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('rendered_solution', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='training.course')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='training.topic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
