# Generated by Django 3.2.6 on 2021-08-04 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='allowed_teachers',
            field=models.ManyToManyField(blank=True, related_name='visible_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
