# Generated by Django 3.2.6 on 2021-08-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_course_allowed_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Very easy'), (1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Very hard')]),
        ),
    ]
