# Generated by Django 3.2.6 on 2021-08-04 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0003_alter_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='item_type',
            field=models.CharField(choices=[('e', 'Programming exercises'), ('q', 'Questions')], default='q', max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question', to='training.course'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question', to='training.topic'),
        ),
        migrations.CreateModel(
            name='ProgrammingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(0, 'Very easy'), (1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Very hard')])),
                ('imported_from_exam', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('rendered_text', models.TextField(blank=True)),
                ('initial_code', models.TextField(blank=True)),
                ('minimum_passing_testcases', models.PositiveSmallIntegerField(default=1)),
                ('solution', models.TextField(blank=True)),
                ('rendered_solution', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programmingexercise', to='training.course')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programmingexercise', to='training.topic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
