# Generated by Django 3.2.6 on 2021-08-04 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0005_rename_item_type_topic_items_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rendered_text', models.TextField(blank=True)),
                ('correct', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GivenAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseOutcomeThroughModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField()),
                ('details', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='trainingtemplaterule',
            name='difficulty',
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('course', 'name'), name='same_course_topic_name_unique'),
        ),
        migrations.AddField(
            model_name='testcaseoutcomethroughmodel',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.exercisesubmission'),
        ),
        migrations.AddField(
            model_name='testcaseoutcomethroughmodel',
            name='testcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.exercisetestcase'),
        ),
        migrations.AddField(
            model_name='givenanswer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.choice'),
        ),
        migrations.AddField(
            model_name='givenanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_answers', to='training.question'),
        ),
        migrations.AddField(
            model_name='givenanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercisetestcase',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='training.programmingexercise'),
        ),
        migrations.AddField(
            model_name='exercisesubmission',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='training.programmingexercise'),
        ),
        migrations.AddField(
            model_name='exercisesubmission',
            name='outcomes',
            field=models.ManyToManyField(through='training.TestCaseOutcomeThroughModel', to='training.ExerciseTestCase'),
        ),
        migrations.AddField(
            model_name='exercisesubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='training.question'),
        ),
    ]
