# Generated by Django 3.2.6 on 2021-08-08 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20210804_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingtemplaterule',
            name='amount',
        ),
        migrations.AddField(
            model_name='trainingtemplate',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_templates', to='training.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingtemplaterule',
            name='amount_easy',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingtemplaterule',
            name='amount_hard',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingtemplaterule',
            name='amount_medium',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingtemplaterule',
            name='amount_very_easy',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingtemplaterule',
            name='amount_very_hard',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingtemplaterule',
            name='difficulty_profile_code',
            field=models.CharField(choices=[('easy_only', 'Easy only'), ('hard_only', 'Hard only'), ('mostly_easy', 'Mostly easy'), ('mostly_hard', 'Mostly hard'), ('balanced', 'Balanced')], default=0, max_length=11),
            preserve_default=False,
        ),
    ]
