# Generated by Django 3.2.6 on 2021-08-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20210808_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtemplaterule',
            name='amount_easy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainingtemplaterule',
            name='amount_hard',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainingtemplaterule',
            name='amount_medium',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainingtemplaterule',
            name='amount_very_easy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainingtemplaterule',
            name='amount_very_hard',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
