# Generated by Django 3.2.6 on 2021-08-09 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0008_auto_20210808_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mode', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Via direct link'), (1, 'Via course search')], null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTrainingSessionThroughModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='programmingexercise',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(0, 'very_easy'), (1, 'easy'), (2, 'medium'), (3, 'hard'), (4, 'very_hard')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(0, 'very_easy'), (1, 'easy'), (2, 'medium'), (3, 'hard'), (4, 'very_hard')]),
        ),
        migrations.DeleteModel(
            name='GivenAnswer',
        ),
        migrations.AddField(
            model_name='questiontrainingsessionthroughmodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.question'),
        ),
        migrations.AddField(
            model_name='questiontrainingsessionthroughmodel',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='training.choice'),
        ),
        migrations.AddField(
            model_name='questiontrainingsessionthroughmodel',
            name='training_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.trainingsession'),
        ),
        migrations.AddField(
            model_name='course',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', through='training.Enrollment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='assigned_in_sessions', through='training.QuestionTrainingSessionThroughModel', to='training.Question'),
        ),
    ]
