# Generated by Django 3.2.6 on 2021-08-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_auto_20210809_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingsession',
            old_name='timestamp',
            new_name='begin_timestamp',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='end_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
    ]
