# Generated by Django 3.2.6 on 2021-08-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_auto_20210810_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontrainingsessionthroughmodel',
            name='position',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
