# Generated by Django 3.2.6 on 2021-08-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_auto_20210811_1706'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trainingtemplaterule',
            constraint=models.UniqueConstraint(fields=('topic', 'training_template'), name='topic_template_unique'),
        ),
    ]
