# Generated by Django 3.2.7 on 2021-09-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_alter_questiontrainingsessionthroughmodel_selected_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='exercisesubmission',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='exercisetestcase',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='questiontrainingsessionthroughmodel',
            options={'ordering': ['training_session_id', 'position']},
        ),
        migrations.AlterModelOptions(
            name='testcaseoutcomethroughmodel',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='trainingsession',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='trainingtemplate',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='trainingtemplaterule',
            options={'ordering': ['pk']},
        ),
    ]
