# Generated by Django 3.2.7 on 2021-09-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_auto_20210928_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='programmingexercise',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['pk']},
        ),
    ]
