# Generated by Django 3.2.7 on 2021-10-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_auto_20210928_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesubmission',
            name='error',
            field=models.TextField(blank=True),
        ),
    ]
