# Generated by Django 3.2.7 on 2021-10-05 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0019_alter_choice_correct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['pk'], 'verbose_name_plural': 'choices'},
        ),
        migrations.AlterModelOptions(
            name='exercisetestcase',
            options={'ordering': ['pk'], 'verbose_name_plural': 'testcases'},
        ),
        migrations.AlterModelOptions(
            name='programmingexercise',
            options={'ordering': ['pk'], 'verbose_name': 'exercise'},
        ),
        migrations.AddField(
            model_name='exercisesubmission',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
