# Generated by Django 3.2.7 on 2021-10-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0020_auto_20211005_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_open_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questiontrainingsessionthroughmodel',
            name='open_answer_text',
            field=models.TextField(blank=True),
        ),
    ]
