# Generated by Django 3.2.7 on 2021-10-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0021_auto_20211005_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingsession',
            options={'ordering': ['course_id', '-begin_timestamp']},
        ),
    ]
