# Generated by Django 3.2.7 on 2021-10-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_alter_trainingsession_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('course', 'text'), name='same_course_question_text_unique'),
        ),
    ]
