# Generated by Django 3.2.7 on 2021-10-11 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0025_questiontrainingsessionthroughmodel_same_session_unique_position'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='programmingexercise',
            name='same_course_programmingexercise_text_unique',
        ),
        migrations.RemoveConstraint(
            model_name='question',
            name='same_course_question_text_unique',
        ),
    ]
