# Generated by Django 3.2.7 on 2021-10-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0025_questiontrainingsessionthroughmodel_same_session_unique_position'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='questiontrainingsessionthroughmodel',
            constraint=models.UniqueConstraint(fields=('training_session', 'question_id'), name='same_session_unique_question'),
        ),
    ]
